# Generated by Django 4.2.7 on 2024-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="main_photo",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
