# Generated by Django 4.2.7 on 2024-02-21 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_video_main_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price_discount",
        ),
    ]
