# Generated by Django 4.2.7 on 2024-02-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_remove_course_price_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="course",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="exam.course"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="main_photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
