# Generated by Django 4.2.7 on 2024-02-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0004_remove_course_video_video_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="courses", to="exam.course"
            ),
        ),
    ]
